# app.py settings
QUEUE_PROCESS_AMT = 2000
QUEUE_PROCESS_DELAY = 10

# guielements.py settings
START = '1.0'
LINES_BUFFER_SIZE = 500
LINES_BUFFER_LOW_CUTOFF = 0.49
LINES_BUFFER_HIGH_CUTOFF = 0.51
MOVETO_YVIEW = 0.5
MAX_LINES_JUMP = 40
MAX_JUMP_CUTOFF = float(MAX_LINES_JUMP) / LINES_BUFFER_SIZE
REDIR_STDOUT = False

# contextmanager.py settings
PYDA_SEP = 'P_'
PYDA_SECTION = PYDA_SEP + 'S'
PYDA_ADDRESS = PYDA_SEP + 'A'
PYDA_MNEMONIC = PYDA_SEP + 'M'
PYDA_OP_STR = PYDA_SEP + 'O'
PYDA_COMMENT = PYDA_SEP + 'C'
PYDA_GENERIC = PYDA_SEP + 'G'
PYDA_ENDL = PYDA_SEP + 'N'
